{{- if and (not .Values.discord.passwordSecret) (.Values.discord.token) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}-discord
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: {{ template "factorio-server-charts.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  token:  {{ .Values.discord.token | b64enc }}
  factorio_channel_id:  {{ .Values.discord.factorio_channel_id | b64enc }}
{{- end }}
